---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'

      - name: Install dependencies
        run: |
          cpanm --notest --installdeps .
          cpanm Test::Most

      - name: Run tests
        run: |
          prove -l
