---
name: Test on Ubuntu
permissions:
  contents: read

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '12 23 7 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'

      - name: Install dependencies
        run: |
          cpanm --notest --installdeps .
          cpanm Test::Most

      - name: Run tests
        run: |
          prove -l
